"$schema" = "schemas/schema.json"

[default]
description = "Default permissions for the plugin"
permissions = [
  "allow-get-auth-details",
  "allow-set-auth-details",
  "allow-clear-auth-details",
  "allow-refresh-token",
  "allow-set-region",
  "allow-fetch-last-moment",
  "allow-compress-webp-to-size",
  "allow-convert-jpeg-to-webp",
  "allow-request-permissions",
]
