name: 'Build'

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build-desktop:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libgtk-3-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install dependencies
        run: pnpm install

      - name: Build frontend
        run: pnpm build:web

      - name: Build the app
        run: pnpm tauri build

      - name: List build directory (macOS)
        if: matrix.platform == 'macos-latest'
        run: |
          ls -R src-tauri/target/release/bundle/

      - name: Upload macOS artifacts
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: StayReal-macOS
          path: |
            src-tauri/target/release/bundle/**/*.app
            src-tauri/target/release/bundle/**/*.dmg
          if-no-files-found: error

      - name: Upload artifacts (Ubuntu)
        if: matrix.platform == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: StayReal-Linux
          path: |
            src-tauri/target/release/bundle/linux/*.deb
            src-tauri/target/release/bundle/linux/*.AppImage
          if-no-files-found: error

      - name: Upload artifacts (Windows)
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: StayReal-Windows
          path: |
            src-tauri/target/release/bundle/windows/*.msi
            src-tauri/target/release/*.exe
          if-no-files-found: error

  build-mobile:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest]
        target: [android, ios]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Java (Android only)
        if: matrix.target == 'android'
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK (Android only)
        if: matrix.target == 'android'
        uses: android-actions/setup-android@v3

      - name: Install Android NDK (Android only)
        if: matrix.target == 'android'
        run: |
          sdkmanager --install "ndk;25.2.9519653"
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/25.2.9519653" >> $GITHUB_ENV
          echo "NDK_HOME=$ANDROID_SDK_ROOT/ndk/25.2.9519653" >> $GITHUB_ENV

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install iOS dependencies
        if: matrix.target == 'ios'
        run: |
          rustup target add aarch64-apple-ios aarch64-apple-ios-sim x86_64-apple-ios
          xcode-select --install || true

      - name: Install Android targets (Android only)
        if: matrix.target == 'android'
        run: |
          rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android
          cargo install cargo-ndk

      - name: Install dependencies
        run: pnpm install

      - name: Build frontend
        run: pnpm build:web

      - name: Build Android App
        if: matrix.target == 'android'
        env:
          NDK_HOME: ${{ env.NDK_HOME }}
        run: |
          pnpm tauri android init
          pnpm tauri android build

      - name: Build iOS App
        if: matrix.target == 'ios'
        run: |
          pnpm tauri ios init
          pnpm tauri ios build

      - name: Upload Android artifacts
        if: matrix.target == 'android'
        uses: actions/upload-artifact@v3
        with:
          name: StayReal-Android
          path: |
            src-tauri/gen/android/app/build/outputs/apk/universal/release/*.apk
            src-tauri/gen/android/app/build/outputs/bundle/universalRelease/*.aab
          if-no-files-found: error

      - name: Upload iOS artifacts
        if: matrix.target == 'ios'
        uses: actions/upload-artifact@v3
        with:
          name: StayReal-iOS
          path: |
            src-tauri/gen/ios/build/*.ipa
            src-tauri/gen/ios/build/*.app
          if-no-files-found: warn